### ISSUE TITLE
Allow User to add tags to their new story link

### ISSUE THREAD

**Issue by heykc** [Now-Loading/ChainLetter#26]
## Description
Add a new field in the AddStory component to allow for a user to add tags to their story link. Users should only be able to add 3 tags in total to a link. Each tag should be separated by a comma. When a comma is typed, the typed word should turn into static text and a hashtag should be added to the beginning of the word. the input field would then move to allow room for the newly added tag. The field should not allow any special characters (including spaces) aside from a comma.

## Acceptance Criteria
- additional field should be added to the AddStory component
- user should be able to type in this field
- user should be able to add a tag by typing a word and then a comma or just pressing enter
- user should only be able to add 3 tags total
- user should be able to delete a tag by backspacing once when there is no text in the input field.
- When submitted, tags should be sent to firestore as an array.

## Notes
This could be a somewhat difficult task. I'd be happy to work on it with you as a pair programmer. 

## Linked Issues
Subtask of #15

**Comment by conorkenahan** [comment]
i can take this one!
